server:
  port: 8701

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false

    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/product-service/**

  main:
    web-application-type: reactive

  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: KuzPsina
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: 82ca8cddc92198c43eeba394e706e16e850062004c1fb5cddbefdfdbf217ebda
      expiration: 86400000
      refresh-token:
        expiration: 604800000
